# fly.toml app configuration file generated for u-starter-patient-wildflower-9903 on 2026-03-26T08:29:58+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'u-starter-patient-wildflower-9903'
primary_region = 'sin'

[experimental]

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOW_PASSWORD_AUTH = 'false'
  ALLOW_ROOT_LOGIN = 'false'
  CF_USE_QUICK_TUNNEL = 'false'
  PERSISTENT_DIR = '/data'
  SSH_USERNAME = 'dev'

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
